import { Dialog, DialogTitle, DialogContent, DialogActions, Button, Grid, Typography, Box, Chip, Divider } from "@mui/material";
import { GeneratedReport } from "../types/reportingTypes";
import { brandColors } from "../../../theme";

interface ReportMetadataDialogProps {
  open: boolean;
  onClose: () => void;
  report: GeneratedReport | null;
}

export function ReportMetadataDialog({ open, onClose, report }: ReportMetadataDialogProps) {
  if (!report) return null;

  return (
    <Dialog open={open} onClose={onClose} maxWidth="sm" fullWidth>
      <DialogTitle sx={{ borderBottom: 1, borderColor: "divider", pb: 1.5 }}>
        <Box sx={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
          <Typography sx={{ fontSize: 16, fontWeight: 700, color: brandColors.sectionTitle }}>
            Report Traceability Metadata
          </Typography>
          <Chip size="small" label={report.status} color="success" />
        </Box>
        <Typography sx={{ fontSize: 12, color: "text.secondary" }}>
          Report ID: <strong>{report.id}</strong> · {report.purpose}
        </Typography>
      </DialogTitle>

      <DialogContent sx={{ pt: 2.5 }}>
        <Grid container spacing={2}>
          <Grid item xs={6}>
            <Typography sx={{ fontSize: 11, color: "text.secondary" }}>Report Name</Typography>
            <Typography sx={{ fontSize: 13, fontWeight: 600 }}>{report.name}</Typography>
          </Grid>

          <Grid item xs={6}>
            <Typography sx={{ fontSize: 11, color: "text.secondary" }}>Report Type</Typography>
            <Typography sx={{ fontSize: 13 }}>{report.type}</Typography>
          </Grid>

          <Grid item xs={6}>
            <Typography sx={{ fontSize: 11, color: "text.secondary" }}>Generated By</Typography>
            <Typography sx={{ fontSize: 13, fontWeight: 600 }}>{report.generatedBy} (ID: {report.generatedByUserId})</Typography>
          </Grid>

          <Grid item xs={6}>
            <Typography sx={{ fontSize: 11, color: "text.secondary" }}>Generated Timestamp</Typography>
            <Typography sx={{ fontSize: 13 }}>{report.generatedOn}</Typography>
          </Grid>

          <Grid item xs={6}>
            <Typography sx={{ fontSize: 11, color: "text.secondary" }}>Reporting Period</Typography>
            <Typography sx={{ fontSize: 13 }}>{report.period}</Typography>
          </Grid>

          <Grid item xs={6}>
            <Typography sx={{ fontSize: 11, color: "text.secondary" }}>Document Version</Typography>
            <Typography sx={{ fontSize: 13 }}>{report.version}</Typography>
          </Grid>

          <Grid item xs={12}>
            <Divider sx={{ my: 0.5 }} />
            <Typography sx={{ fontSize: 11, color: "text.secondary", mb: 0.5 }}>Source Record IDs Included</Typography>
            <Box sx={{ display: "flex", flexWrap: "wrap", gap: 0.5 }}>
              {report.sourceRecordIds.map((id) => (
                <Chip key={id} size="small" label={`Rec #${id}`} variant="outlined" sx={{ fontSize: 10, height: 20 }} />
              ))}
            </Box>
          </Grid>

          <Grid item xs={12}>
            <Typography sx={{ fontSize: 11, color: "text.secondary", mb: 0.5 }}>Applied Criteria</Typography>
            <Box sx={{ p: 1.5, bgcolor: "#f8fafc", borderRadius: 1, border: "1px solid #e2e8f0", fontSize: 11, fontFamily: "monospace", overflowX: "auto" }}>
              {report.criteriaJson}
            </Box>
          </Grid>

          {report.auditTrailRef && (
            <Grid item xs={12}>
              <Typography sx={{ fontSize: 11, color: "text.secondary" }}>Audit Trail Reference</Typography>
              <Typography sx={{ fontSize: 12, fontFamily: "monospace" }}>{report.auditTrailRef}</Typography>
            </Grid>
          )}
        </Grid>
      </DialogContent>

      <DialogActions sx={{ px: 3, py: 1.5, borderTop: 1, borderColor: "divider" }}>
        <Button onClick={onClose}>Close</Button>
      </DialogActions>
    </Dialog>
  );
}
