import { Dialog, DialogTitle, DialogContent, DialogActions, Button, Box, Typography, Table, TableHead, TableRow, TableCell, TableBody, Chip, useTheme } from "@mui/material";
import PrintIcon from "@mui/icons-material/Print";
import CloseIcon from "@mui/icons-material/Close";
import { ReportBuilderOptions, ReportPreviewData } from "../types/reportingTypes";
import { StatusBadge } from "../../../components/StatusBadge";
import { brandColors } from "../../../theme";

interface ReportPreviewModalProps {
  open: boolean;
  onClose: () => void;
  previewData: ReportPreviewData | null;
  options: ReportBuilderOptions;
}

export function ReportPreviewModal({ open, onClose, previewData, options }: ReportPreviewModalProps) {
  const theme = useTheme();
  if (!previewData) return null;

  const handlePrint = () => {
    window.print();
  };

  return (
    <Dialog open={open} onClose={onClose} maxWidth="lg" fullWidth scroll="paper">
      <DialogTitle sx={{ display: "flex", justifyContent: "space-between", alignItems: "center", borderBottom: 1, borderColor: "divider", bgcolor: "background.paper" }}>
        <Box sx={{ display: "flex", alignItems: "center", gap: 1.5 }}>
          <Typography sx={{ fontSize: 18, fontWeight: 700, color: theme.palette.primary.main }}>
            Full Report Preview
          </Typography>
          <Chip size="small" label={previewData.reportPurpose} sx={{ bgcolor: brandColors.causeBadgeBg, color: brandColors.causeBadgeText, fontWeight: 700 }} />
        </Box>
        <Box sx={{ display: "flex", gap: 1 }}>
          <Button variant="contained" size="small" startIcon={<PrintIcon />} onClick={handlePrint}>
            Print / Save as PDF
          </Button>
          <Button variant="outlined" size="small" startIcon={<CloseIcon />} onClick={onClose}>
            Close
          </Button>
        </Box>
      </DialogTitle>

      <DialogContent sx={{ p: 4, bgcolor: "background.default" }}>
        <Box sx={{ maxWidth: "850px", mx: "auto", p: 4, bgcolor: "background.paper", borderRadius: 2, boxShadow: theme.palette.mode === "dark" ? "0 2px 10px rgba(0,0,0,0.4)" : "0 2px 10px rgba(0,0,0,0.06)", border: "1px solid", borderColor: "divider" }}>
          {/* Header */}
          <Box sx={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", pb: 2, mb: 3, borderBottom: "2px solid #7b2d8e" }}>
            <Box>
              <Typography sx={{ fontSize: 12, fontWeight: 700, color: theme.palette.primary.main, textTransform: "uppercase", letterSpacing: 1 }}>
                MicroLIMS Laboratory Report
              </Typography>
              <Typography sx={{ fontSize: 22, fontWeight: 800, color: "text.primary", mt: 0.5 }}>
                {previewData.reportTitle}
              </Typography>
              <Typography sx={{ fontSize: 13, color: "text.secondary", mt: 0.5 }}>
                {previewData.reportingPeriod}
              </Typography>
            </Box>
            <Box sx={{ textAlign: "right" }}>
              <Typography sx={{ fontSize: 11, color: "text.secondary" }}>{previewData.generatedAt}</Typography>
              <Typography sx={{ fontSize: 11, color: "text.secondary" }}>Generated by: {previewData.generatedByName}</Typography>
              <Chip size="small" label={previewData.reportPurpose} variant="outlined" sx={{ mt: 1, fontSize: 10, height: 20 }} />
            </Box>
          </Box>

          {/* Groups & Tables */}
          {previewData.groups.map((group, idx) => (
            <Box key={idx} sx={{ mb: 3 }}>
              <Typography sx={{ fontSize: 14, fontWeight: 700, color: theme.palette.primary.main, mb: 1, bgcolor: "background.default", px: 1.5, py: 0.75, borderRadius: 1 }}>
                {group.groupTitle} ({group.items.length} records)
              </Typography>

              <Table size="small" sx={{ "& th": { bgcolor: "background.default", fontWeight: 700, fontSize: 11.5 }, "& td": { fontSize: 12 } }}>
                <TableHead>
                  <TableRow>
                    <TableCell>Sample/Reference</TableCell>
                    <TableCell>Product / Item</TableCell>
                    <TableCell>Test</TableCell>
                    <TableCell>Result</TableCell>
                    {options.includeSpecifications && <TableCell>Specification</TableCell>}
                    {options.includeLimits && <TableCell>Alert / Action</TableCell>}
                    <TableCell>Result Level</TableCell>
                    <TableCell>Status</TableCell>
                    {options.includeAnalyst && <TableCell>Analyst</TableCell>}
                    {options.includeApprovalInfo && <TableCell>Approved By</TableCell>}
                  </TableRow>
                </TableHead>
                <TableBody>
                  {group.items.map((row) => (
                    <TableRow key={row.id} hover>
                      <TableCell sx={{ fontWeight: 600 }}>{row.referenceNumber}</TableCell>
                      <TableCell>{row.subjectName}</TableCell>
                      <TableCell>{row.testDisplayName || row.testCode}</TableCell>
                      <TableCell sx={{ fontWeight: 700, color: theme.palette.primary.main }}>{row.reportedValue} {row.unit ?? ""}</TableCell>
                      {options.includeSpecifications && <TableCell>{row.specLimit ?? "—"}</TableCell>}
                      {options.includeLimits && <TableCell>{row.alertLimit ? `${row.alertLimit} / ${row.actionLimit}` : "—"}</TableCell>}
                      <TableCell><StatusBadge status={row.resultLevel} /></TableCell>
                      <TableCell><StatusBadge status={row.approvalStatus} /></TableCell>
                      {options.includeAnalyst && <TableCell>{row.resultEnteredByName}</TableCell>}
                      {options.includeApprovalInfo && <TableCell>{row.approvedByName ?? "Pending"}</TableCell>}
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </Box>
          ))}

          {/* Signatures & Footer if toggled */}
          {options.includeSignatures && (
            <Box sx={{ mt: 4, pt: 3, borderTop: "1px solid", borderColor: "divider" }}>
              <Typography sx={{ fontSize: 12, fontWeight: 700, color: "text.secondary", mb: 2, textTransform: "uppercase" }}>
                Electronic Signatures / Attestations
              </Typography>
              <Box sx={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 3 }}>
                <Box sx={{ p: 2, border: "1px solid", borderColor: "divider", borderRadius: 1, bgcolor: "background.default" }}>
                  <Typography sx={{ fontSize: 11, color: "text.secondary" }}>Generated / Prepared By:</Typography>
                  <Typography sx={{ fontSize: 13, fontWeight: 700 }}>{previewData.generatedByName}</Typography>
                  <Typography sx={{ fontSize: 11, color: "text.secondary", mt: 0.5 }}>{previewData.generatedAt}</Typography>
                </Box>
                <Box sx={{ p: 2, border: "1px solid", borderColor: "divider", borderRadius: 1, bgcolor: "background.default" }}>
                  <Typography sx={{ fontSize: 11, color: "text.secondary" }}>Section Head Review / Authorization:</Typography>
                  <Typography sx={{ fontSize: 13, fontWeight: 700 }}>Quality Microbiology Section Head</Typography>
                  <Typography sx={{ fontSize: 11, color: "text.secondary", mt: 0.5 }}>Electronically verified under 21 CFR Part 11</Typography>
                </Box>
              </Box>
            </Box>
          )}

          {options.includePageNumbers && (
            <Box sx={{ mt: 4, pt: 2, borderTop: "1px solid", borderColor: "divider", display: "flex", justifyContent: "space-between", fontSize: 11, color: "text.secondary" }}>
              <Typography sx={{ fontSize: 11 }}>MicroLIMS Controlled Laboratory Report</Typography>
              <Typography sx={{ fontSize: 11 }}>Page 1 of 1</Typography>
            </Box>
          )}
        </Box>
      </DialogContent>

      <DialogActions sx={{ px: 3, py: 2, borderTop: 1, borderColor: "divider" }}>
        <Button variant="contained" onClick={handlePrint} startIcon={<PrintIcon />}>
          Print / PDF
        </Button>
        <Button onClick={onClose}>Close Preview</Button>
      </DialogActions>
    </Dialog>
  );
}
