// <auto-generated />
using System;
using System.Collections.Generic;
using MicroLIMS.Persistence.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MicroLIMS.Persistence.Migrations
{
    [DbContext(typeof(MicroLimsDbContext))]
    [Migration("20260731084227_AddItemIsActive")]
    partial class AddItemIsActive
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MicroLIMS.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("text");

                    b.Property<string>("ControlNumber")
                        .HasColumnType("text");

                    b.Property<string>("CryovialCode")
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MediaLotNumber")
                        .HasColumnType("text");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("PreviousValue")
                        .HasColumnType("text");

                    b.Property<string>("ReferenceStrainCode")
                        .HasColumnType("text");

                    b.Property<int?>("SampleId")
                        .HasColumnType("integer");

                    b.Property<string>("SampleReferenceNumber")
                        .HasColumnType("text");

                    b.Property<int?>("TestOrderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.CauseOfTesting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CausesOfTesting");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.Cryovial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDestroyed")
                        .HasColumnType("boolean");

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfVialsPrepared")
                        .HasColumnType("integer");

                    b.Property<int>("PassageNumber")
                        .HasColumnType("integer");

                    b.Property<string>("PhysicalCheckText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReferenceStrainId")
                        .HasColumnType("integer");

                    b.Property<string>("StorageCondition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ThawedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceStrainId");

                    b.ToTable("Cryovials");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TestingFrequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.DiluentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("MediaTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequiresBatchTracking")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("MediaTypeId");

                    b.ToTable("DiluentTypes");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.EMRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<List<string>>("SamplingPositions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("EMRooms");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CalibrationDueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("SetPointTemperature")
                        .HasColumnType("numeric");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.EquipmentInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CalibrationDueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("InstrumentType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastModifiedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("EquipmentInventories");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.ExpectedIndicationResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExpectedDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MediaTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("OrganismName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MediaTypeId");

                    b.ToTable("ExpectedIndicationResults");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.GptChallengeResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Atcc")
                        .HasColumnType("text");

                    b.Property<int?>("CryovialId")
                        .HasColumnType("integer");

                    b.Property<string>("ExpectedDescription")
                        .HasColumnType("text");

                    b.Property<string>("InitialInoculum")
                        .HasColumnType("text");

                    b.Property<int>("MediaId")
                        .HasColumnType("integer");

                    b.Property<bool>("NegativeControlGrowth")
                        .HasColumnType("boolean");

                    b.Property<int?>("NewMediaResult")
                        .HasColumnType("integer");

                    b.Property<string>("ObservationText")
                        .HasColumnType("text");

                    b.Property<int?>("OldMediaResult")
                        .HasColumnType("integer");

                    b.Property<string>("OrganismName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Panel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecordedByUserId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("RecoveryPercent")
                        .HasColumnType("numeric");

                    b.Property<string>("TurbidResult")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CryovialId");

                    b.HasIndex("MediaId");

                    b.ToTable("GptChallengeResults");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.IdentityConfirmationEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CryovialId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IncubationEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IncubationStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IncubatorEquipmentId")
                        .HasColumnType("integer");

                    b.Property<int>("MediaId")
                        .HasColumnType("integer");

                    b.Property<string>("ObservationText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ReferenceStrainId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CryovialId");

                    b.HasIndex("IncubatorEquipmentId");

                    b.HasIndex("MediaId");

                    b.HasIndex("ReferenceStrainId");

                    b.ToTable("IdentityConfirmationEntry");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.Incubation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Outcome")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer");

                    b.Property<int>("TestOrderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TestOrderId");

                    b.ToTable("Incubations");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SopNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Items");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.LoginHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LoginHistories");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.MachinePart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MachineId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("MachineParts");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.MachinePartConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionLimit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AlertLimit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPathogenTest")
                        .HasColumnType("boolean");

                    b.Property<int>("MachinePartId")
                        .HasColumnType("integer");

                    b.Property<string>("SpecLimit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TestCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TestType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MachinePartId");

                    b.ToTable("MachinePartConfigurations");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastModifiedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("MaterialType")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MinimumStockLevel")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("QuantityReceived")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("QuantityRemaining")
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime>("ReceivingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Unit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("MaterialType");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AutoclaveEquipmentId")
                        .HasColumnType("integer");

                    b.Property<string>("AutoclaveProgram")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CycleNumber")
                        .HasColumnType("integer");

                    b.Property<int>("CycleTime")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GptStage")
                        .HasColumnType("integer");

                    b.Property<string>("LoadType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ManufacturerLot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("MediaTypeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Ph")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("PreparedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("numeric");

                    b.Property<string>("TotalVolume")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalWeight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AutoclaveEquipmentId");

                    b.HasIndex("LotNumber")
                        .IsUnique();

                    b.HasIndex("MediaTypeId");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.MediaType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<List<string>>("ApprovedTestCodes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Class")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IncubationMaxHours")
                        .HasColumnType("integer");

                    b.Property<int>("IncubationMinHours")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("RecoveryPercentMax")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RecoveryPercentMin")
                        .HasColumnType("numeric");

                    b.Property<decimal>("RequiredTemperatureMax")
                        .HasColumnType("numeric");

                    b.Property<decimal>("RequiredTemperatureMin")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("MediaTypes");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.MediaUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MediaId")
                        .HasColumnType("integer");

                    b.Property<int>("TestOrderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsedByUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.HasIndex("TestOrderId");

                    b.ToTable("MediaUsages");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.Neutralizer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Neutralizers");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.NotificationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EmailSent")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("NotificationLogs");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.PassageEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CryovialId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PassageNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PerformedByUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CryovialId");

                    b.ToTable("PassageEvents");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.PathogenObservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("GrowthObserved")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ObservedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer");

                    b.Property<int>("TestOrderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TestOrderId");

                    b.ToTable("PathogenObservations");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.ReferenceStrain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("integer");

                    b.Property<string>("AtccNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DiscsRemaining")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfDiscs")
                        .HasColumnType("integer");

                    b.Property<string>("OrganismName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PassageNumber")
                        .HasColumnType("integer");

                    b.Property<string>("PhysicalCheckText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReceivedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("StorageCondition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ReferenceStrains");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GeneratedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("PdfPath")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.ReportSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReportId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportSnapshots");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EnteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EnteredByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("InterpretedValue")
                        .HasColumnType("text");

                    b.Property<string>("RawValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TestOrderId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TestOrderId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("GradeClassification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.RoomMonitoring", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsOutOfTrend")
                        .HasColumnType("boolean");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SampledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SamplingPosition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Step1Count")
                        .HasColumnType("integer");

                    b.Property<int>("Step2Count")
                        .HasColumnType("integer");

                    b.Property<int>("TestOrderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("TestOrderId");

                    b.ToTable("RoomMonitorings");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.RoomTestConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionLimit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AlertLimit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<string>("SpecLimit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TestCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TestType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomTestConfigurations");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.Sample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNumber")
                        .HasColumnType("text");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<int>("CauseOfTestingId")
                        .HasColumnType("integer");

                    b.Property<string>("ControlNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int?>("MachineId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("MfgDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PreparationStatus")
                        .HasColumnType("integer");

                    b.Property<string>("ProductionStage")
                        .HasColumnType("text");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReceivedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SampleQuantity")
                        .HasColumnType("text");

                    b.Property<string>("SampledBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StorageCondition")
                        .HasColumnType("text");

                    b.Property<int?>("StorageTimeHours")
                        .HasColumnType("integer");

                    b.Property<int?>("WaterSamplingPointId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CauseOfTestingId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ItemId");

                    b.HasIndex("MachineId");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique();

                    b.HasIndex("WaterSamplingPointId");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.SamplePreparation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int?>("DiluentMediaId")
                        .HasColumnType("integer");

                    b.Property<int>("DiluentTypeId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("FiltrationVolume")
                        .HasColumnType("numeric");

                    b.Property<int>("NeutralizerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PreparedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PreparedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("SampleId")
                        .HasColumnType("integer");

                    b.Property<string>("Technique")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("WashingVolume")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("DiluentMediaId");

                    b.HasIndex("DiluentTypeId");

                    b.HasIndex("NeutralizerId");

                    b.HasIndex("SampleId");

                    b.ToTable("SamplePreparations");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.SampleTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<string>("TestCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("SampleTests");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.SamplingConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionLimit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AlertLimit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpecLimit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TestCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WaterSamplingPointId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WaterSamplingPointId");

                    b.ToTable("SamplingConfigurations");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.Specification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionLimit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AlertLimit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<string>("SpecLimit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TestCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Specifications");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.TestDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TestDefinitions");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.TestOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedAnalystId")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("integer");

                    b.Property<int>("SampleId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TestCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SampleId");

                    b.ToTable("TestOrders");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.WaterSamplingPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<List<string>>("AssignedTestCodes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WaterSamplingPoints");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.WorkflowHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FromStep")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("PerformedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("TestOrderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ToStep")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TestOrderId");

                    b.ToTable("WorkflowHistories");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.Cryovial", b =>
                {
                    b.HasOne("MicroLIMS.Domain.Entities.ReferenceStrain", "ReferenceStrain")
                        .WithMany("Cryovials")
                        .HasForeignKey("ReferenceStrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReferenceStrain");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.DiluentType", b =>
                {
                    b.HasOne("MicroLIMS.Domain.Entities.MediaType", "MediaType")
                        .WithMany()
                        .HasForeignKey("MediaTypeId");

                    b.Navigation("MediaType");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.EMRoom", b =>
                {
                    b.HasOne("MicroLIMS.Domain.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.ExpectedIndicationResult", b =>
                {
                    b.HasOne("MicroLIMS.Domain.Entities.MediaType", "MediaType")
                        .WithMany()
                        .HasForeignKey("MediaTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaType");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.GptChallengeResult", b =>
                {
                    b.HasOne("MicroLIMS.Domain.Entities.Cryovial", "Cryovial")
                        .WithMany()
                        .HasForeignKey("CryovialId");

                    b.HasOne("MicroLIMS.Domain.Entities.Media", "Media")
                        .WithMany("GptResults")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cryovial");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.IdentityConfirmationEntry", b =>
                {
                    b.HasOne("MicroLIMS.Domain.Entities.Cryovial", "Cryovial")
                        .WithMany("IdentityConfirmations")
                        .HasForeignKey("CryovialId");

                    b.HasOne("MicroLIMS.Domain.Entities.Equipment", "IncubatorEquipment")
                        .WithMany()
                        .HasForeignKey("IncubatorEquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MicroLIMS.Domain.Entities.Media", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MicroLIMS.Domain.Entities.ReferenceStrain", "ReferenceStrain")
                        .WithMany("IdentityConfirmations")
                        .HasForeignKey("ReferenceStrainId");

                    b.Navigation("Cryovial");

                    b.Navigation("IncubatorEquipment");

                    b.Navigation("Media");

                    b.Navigation("ReferenceStrain");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.Incubation", b =>
                {
                    b.HasOne("MicroLIMS.Domain.Entities.TestOrder", "TestOrder")
                        .WithMany("Incubations")
                        .HasForeignKey("TestOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestOrder");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.MachinePart", b =>
                {
                    b.HasOne("MicroLIMS.Domain.Entities.Machine", "Machine")
                        .WithMany("Parts")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.MachinePartConfiguration", b =>
                {
                    b.HasOne("MicroLIMS.Domain.Entities.MachinePart", "MachinePart")
                        .WithMany("TestConfigurations")
                        .HasForeignKey("MachinePartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MachinePart");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.Media", b =>
                {
                    b.HasOne("MicroLIMS.Domain.Entities.Equipment", "AutoclaveEquipment")
                        .WithMany()
                        .HasForeignKey("AutoclaveEquipmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MicroLIMS.Domain.Entities.MediaType", "MediaType")
                        .WithMany()
                        .HasForeignKey("MediaTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AutoclaveEquipment");

                    b.Navigation("MediaType");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.MediaUsage", b =>
                {
                    b.HasOne("MicroLIMS.Domain.Entities.Media", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MicroLIMS.Domain.Entities.TestOrder", "TestOrder")
                        .WithMany()
                        .HasForeignKey("TestOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("TestOrder");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.PassageEvent", b =>
                {
                    b.HasOne("MicroLIMS.Domain.Entities.Cryovial", "Cryovial")
                        .WithMany("PassageHistory")
                        .HasForeignKey("CryovialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cryovial");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("MicroLIMS.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.PathogenObservation", b =>
                {
                    b.HasOne("MicroLIMS.Domain.Entities.TestOrder", "TestOrder")
                        .WithMany()
                        .HasForeignKey("TestOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestOrder");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.Permission", b =>
                {
                    b.HasOne("MicroLIMS.Domain.Entities.Role", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("MicroLIMS.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.ReportSnapshot", b =>
                {
                    b.HasOne("MicroLIMS.Domain.Entities.Report", "Report")
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.Result", b =>
                {
                    b.HasOne("MicroLIMS.Domain.Entities.TestOrder", "TestOrder")
                        .WithMany("Results")
                        .HasForeignKey("TestOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestOrder");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("MicroLIMS.Domain.Entities.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MicroLIMS.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.Room", b =>
                {
                    b.HasOne("MicroLIMS.Domain.Entities.Department", "Department")
                        .WithMany("Rooms")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.RoomMonitoring", b =>
                {
                    b.HasOne("MicroLIMS.Domain.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MicroLIMS.Domain.Entities.TestOrder", "TestOrder")
                        .WithMany()
                        .HasForeignKey("TestOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("TestOrder");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.RoomTestConfiguration", b =>
                {
                    b.HasOne("MicroLIMS.Domain.Entities.Room", "Room")
                        .WithMany("TestConfigurations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.Sample", b =>
                {
                    b.HasOne("MicroLIMS.Domain.Entities.CauseOfTesting", "CauseOfTesting")
                        .WithMany()
                        .HasForeignKey("CauseOfTestingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MicroLIMS.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MicroLIMS.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MicroLIMS.Domain.Entities.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MicroLIMS.Domain.Entities.WaterSamplingPoint", "WaterSamplingPoint")
                        .WithMany()
                        .HasForeignKey("WaterSamplingPointId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CauseOfTesting");

                    b.Navigation("Department");

                    b.Navigation("Item");

                    b.Navigation("Machine");

                    b.Navigation("WaterSamplingPoint");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.SamplePreparation", b =>
                {
                    b.HasOne("MicroLIMS.Domain.Entities.Media", "DiluentMedia")
                        .WithMany()
                        .HasForeignKey("DiluentMediaId");

                    b.HasOne("MicroLIMS.Domain.Entities.DiluentType", "DiluentType")
                        .WithMany()
                        .HasForeignKey("DiluentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MicroLIMS.Domain.Entities.Neutralizer", "Neutralizer")
                        .WithMany()
                        .HasForeignKey("NeutralizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MicroLIMS.Domain.Entities.Sample", "Sample")
                        .WithMany()
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiluentMedia");

                    b.Navigation("DiluentType");

                    b.Navigation("Neutralizer");

                    b.Navigation("Sample");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.SampleTest", b =>
                {
                    b.HasOne("MicroLIMS.Domain.Entities.Item", "Item")
                        .WithMany("AssignedTests")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.SamplingConfiguration", b =>
                {
                    b.HasOne("MicroLIMS.Domain.Entities.WaterSamplingPoint", "WaterSamplingPoint")
                        .WithMany()
                        .HasForeignKey("WaterSamplingPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WaterSamplingPoint");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.Specification", b =>
                {
                    b.HasOne("MicroLIMS.Domain.Entities.Item", "Item")
                        .WithMany("Specifications")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.TestOrder", b =>
                {
                    b.HasOne("MicroLIMS.Domain.Entities.Sample", "Sample")
                        .WithMany("TestOrders")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sample");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.User", b =>
                {
                    b.HasOne("MicroLIMS.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.WorkflowHistory", b =>
                {
                    b.HasOne("MicroLIMS.Domain.Entities.TestOrder", "TestOrder")
                        .WithMany("WorkflowHistory")
                        .HasForeignKey("TestOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestOrder");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.Cryovial", b =>
                {
                    b.Navigation("IdentityConfirmations");

                    b.Navigation("PassageHistory");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.Department", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.Item", b =>
                {
                    b.Navigation("AssignedTests");

                    b.Navigation("Specifications");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.Machine", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.MachinePart", b =>
                {
                    b.Navigation("TestConfigurations");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.Media", b =>
                {
                    b.Navigation("GptResults");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.ReferenceStrain", b =>
                {
                    b.Navigation("Cryovials");

                    b.Navigation("IdentityConfirmations");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.Room", b =>
                {
                    b.Navigation("TestConfigurations");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.Sample", b =>
                {
                    b.Navigation("TestOrders");
                });

            modelBuilder.Entity("MicroLIMS.Domain.Entities.TestOrder", b =>
                {
                    b.Navigation("Incubations");

                    b.Navigation("Results");

                    b.Navigation("WorkflowHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
