-- Physicochemical laboratory equipment inventory (source: "physiochemical list of equipments.docx").
-- Idempotent: a row is skipped when its Code already exists. Section 2 = Physicochemical Laboratory.
-- EquipmentType ints: 5 Other, 6 Hplc, 7 PhMeter, 8 Balance, 10 UvVis, 11 Dissolution, 12 Disintegration,
-- 13 KarlFischer, 14 Titrator, 15 Viscometer, 16 Refractometer, 17 Polarimeter, 18 Conductivity,
-- 19 MeltingPoint, 20 Oven, 21 Furnace, 22 Gc, 23 Aas, 24 DigestionMicrowave, 25 Caliper.
-- CdsSoftware ints: 1 AgilentOpenLab, 2 WatersEmpower3.
INSERT INTO "Equipment" ("Code","Name","Type","Location","Vendor","CdsSoftware","SectionId")
SELECT v.code, v.name, v.type, v.loc, v.vendor, v.cds, 2
FROM (VALUES
 ('BLC-F-IL-F-09-046','Shimadzu Digital Balance',8,'Instruments lab','Shimadzu',NULL::int),
 ('UVS-F-IL-F-08-030','Varian UV Spectrophotometer',10,'Instruments lab','Varian',NULL),
 ('HPC-F-IL-F-08-028','Agilent HPLC',6,'Instruments lab','Agilent',1),
 ('HPC-F-IL-F-08-041','Waters HPLC',6,'Instruments lab','Waters',2),
 ('HPC-F-IL-F-08-057','Waters HPLC',6,'Instruments lab','Waters',2),
 ('HPC-F-IL-F-08067','Shimadzu HPLC',6,'Instruments lab','Shimadzu',NULL),
 ('ICP-F-IL-F-11-069','Perkinelmer ICP',9,'Instruments lab','Perkinelmer',3),
 ('GCS-F-IL-F-11-068','Shimadzu GC',22,'Instruments lab','Shimadzu',NULL),
 ('DCL-F-PK-F-05-026','Mitutoyo Digital Caliper',25,'Packaging material lab','Mitutoyo',NULL),
 ('MCM-F-PK-F-05-035','Mitutoyo Micrometer',5,'Packaging material lab','Mitutoyo',NULL),
 ('DSS-F-WL-F-01-009','Electrolab Dissolution Tester',11,'Wet chemical lab','Electrolab',NULL),
 ('SOC-F-WL-F-01-065','DAIHAN Sonicator',5,'Wet chemical lab','DAIHAN Scientific',NULL),
 ('MIX-F-WL-F-01-016','Stuart Hot Plate/Stirrer',5,'Wet chemical lab','Stuart',NULL),
 ('MIX-F-WL-F-01-013','Fisher Magnetic Stirrer',5,'Wet chemical lab','Fisher Scientific',NULL),
 ('WES-F-WL-F-01-014','Superfit Weights Set',5,'Wet chemical lab','Superfit',NULL),
 ('BLC-F-WL-F-01-047','Shimadzu Digital Balance',8,'Wet chemical lab','Shimadzu',NULL),
 ('PHM-F-WL-F-01-001','Jenway pH Meter',7,'Wet chemical lab','Jenway',NULL),
 ('VIS-F-WL-F-01-003','Brookfield Viscometer',15,'Wet chemical lab','Brookfield',NULL),
 ('PHC-F-WL-F-01-007','Adwa pH/TDS/Conductivity Meter',18,'Wet chemical lab','Adwa',NULL),
 ('OVN-F-WL-F-01-011','Carbolite Oven',20,'Wet chemical lab','Carbolite',NULL),
 ('RFM-F-WL-F-01-017','OPTIKA Refractometer',16,'Wet chemical lab','OPTIKA',NULL),
 ('PLM-F-WL-F-01-018','Anton Paar Polarimeter',17,'Wet chemical lab','Anton Paar',NULL),
 ('DST-F-WL-F-01-040','Pure Enterprises Disintegration Tester',12,'Wet chemical lab','Pure Enterprises',NULL),
 ('MLP-F-WL-F-01-042','Stuart Melting Point Apparatus',19,'Wet chemical lab','Stuart',NULL),
 ('CNF-F-WL-F-01-021','SCILOGEX Centrifuge',5,'Wet chemical lab','SCILOGEX',NULL),
 ('PUP-F-WL-F-01-022','VALUE Vacuum Pump',5,'Wet chemical lab','VALUE',NULL),
 ('DSW-F-WL-F-01-45','Chrono Digital Stopwatch',5,'Wet chemical lab','Chrono',NULL),
 ('OVN-F-WL-F-01-053','LTE Scientific Drying Cabinet',20,'Wet chemical lab','LTE Scientific',NULL),
 ('MCW-F-IL-F-10-044','Milestone Digestion Microwave',24,'Wet chemical lab','Milestone',NULL),
 ('WDS-F-WL-F-01-043','Boeco Water Distiller',5,'Wet chemical lab','Boeco',NULL),
 ('THE-F-WL-F-01-056','Glass Thermometer',5,'Wet chemical lab',NULL,NULL),
 ('ATM-F-IL-F-11-063','Varian Atomic Absorption Spectrometer',23,'Instruments lab','Varian',NULL),
 ('KAF-F-WL-F-01-020','Spectra Lab Karl Fischer',13,'Wet chemical lab','Spectra Lab',NULL),
 ('HOD-F-IL-F-10-032','Fume Hood',5,'Instruments lab',NULL,NULL),
 ('HOD-F-IL-F-11-034','CHIMNEY Fume Hood',5,'Instruments lab','CHIMNEY',NULL),
 ('HOD-F-WL-F-01-024','Fume Hood',5,'Wet chemical lab',NULL,NULL),
 ('CID-F-PK-F-05-051','X-Rite Cap Sure',5,'Packaging material lab','X-Rite',NULL),
 ('COD-F-WL-F-01-049','LG Refrigerator',5,'Wet chemical lab','LG',NULL),
 ('TRH-F-PK-F-05-037','Digital Thermometer/Hygrometer',5,'Packaging material lab',NULL,NULL),
 ('TRH-F-WL-F-01-038','Digital Thermometer/Hygrometer',5,'Wet chemical lab',NULL,NULL),
 ('TRH-F-IL-F-08-039','Digital Thermometer/Hygrometer',5,'Instruments lab',NULL,NULL),
 ('OVN-F-WL-F-01-015','Nabertherm Muffle Furnace',21,'Instruments lab','Nabertherm GmbH',NULL),
 ('THE-F-WL-F-01-006','HTC Digital Thermometer',5,'Wet lab LG Refrigerator','HTC',NULL),
 ('THE-F-WL-F-01-050','Testo Temperature Data Logger',5,'Wet lab LG Refrigerator (Freezer)','Testo',NULL),
 ('THE-F-WL-F-01-067','Testo Temperature Data Logger',5,'Wet lab LG Refrigerator','Testo',NULL),
 ('RUL-F-PK-F-05-058','Ruler (30 cm)',5,'Packaging material lab',NULL,NULL),
 ('RUL-F-PK-F-05-059','Ruler (30 cm)',5,'Packaging material lab',NULL,NULL),
 ('RUL-F-PK-F-05-060','Ruler (50 cm)',5,'Packaging material lab',NULL,NULL),
 ('RUL-F-PK-F-05-061','Ruler (100 cm)',5,'Packaging material lab',NULL,NULL),
 ('RUL-F-PK-F-05-062','Ruler (100 cm)',5,'Packaging material lab',NULL,NULL),
 ('KAF-F-PK-F-05-063','Metrohm Karl Fischer',13,'Packaging material lab','Metrohm',NULL),
 ('POT-F-PK-F-05-064','Metrohm Potentiometric Titrator',14,'Packaging material lab','Metrohm',NULL)
) AS v(code,name,type,loc,vendor,cds)
WHERE NOT EXISTS (SELECT 1 FROM "Equipment" e WHERE e."Code" = v.code);
