using System.Security.Cryptography;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using MicroLIMS.Domain.Entities;
using MicroLIMS.Domain.Enums;
using MicroLIMS.Infrastructure.Storage;
using MicroLIMS.Persistence.DbContext;

namespace MicroLIMS.Application.Services;

public record UploadEquipmentDocumentRequest(
    EquipmentDocumentType DocumentType,
    string OriginalFileName,
    string DeclaredContentType,
    byte[] Content);

public record SupersedeEquipmentDocumentRequest(
    string OriginalFileName,
    string DeclaredContentType,
    byte[] Content,
    string Reason);

public record VoidEquipmentDocumentRequest(string Reason);

public record EquipmentDocumentDto(
    int Id,
    int EquipmentInventoryId,
    EquipmentDocumentType DocumentType,
    string OriginalFileName,
    string FileExtension,
    string ContentType,
    long FileSizeBytes,
    string ContentSha256,
    int UploadedByUserId,
    string UploadedByName,
    DateTime UploadedAt,
    MaterialDocumentStatus Status,
    int? SupersededByDocumentId,
    DateTime? SupersededAt,
    int? SupersededByUserId,
    string? SupersessionReason,
    DateTime? VoidedAt,
    int? VoidedByUserId,
    string? VoidReason);

// Service managing the controlled document lifecycle for Equipment.
// Reuses the shared IFileStorageService and MaterialDocumentFileValidator.
//
// Key principles:
// 1. Files are NEVER overwritten on disk.
// 2. Storage keys are generated by the server: equipment-documents/{equipmentId}/{documentId}{ext}
// 3. Document integrity is checked via SHA-256 on every content retrieval.
// 4. Access events (View, Download) are logged in EquipmentDocumentAccessLog.
// 5. Supersession atomically marks the previous document Superseded and creates a new Current document.
// 6. Voiding retains the file and metadata for audit but marks the document Voided.
public class EquipmentDocumentService
{
    private readonly MicroLimsDbContext _db;
    private readonly IFileStorageService _storage;
    private readonly MaterialDocumentFileValidator _validator;
    private readonly ILogger<EquipmentDocumentService> _logger;

    public EquipmentDocumentService(
        MicroLimsDbContext db,
        IFileStorageService storage,
        MaterialDocumentFileValidator validator,
        ILogger<EquipmentDocumentService> logger)
    {
        _db = db;
        _storage = storage;
        _validator = validator;
        _logger = logger;
    }

    // ---- List ----

    public async Task<List<EquipmentDocumentDto>> GetDocumentsAsync(int equipmentId, int requestingUserId)
    {
        var equipmentExists = await _db.EquipmentInventories.AnyAsync(e => e.Id == equipmentId);
        if (!equipmentExists)
            throw new InvalidOperationException($"Equipment {equipmentId} not found.");

        var docs = await _db.EquipmentDocuments
            .Where(d => d.EquipmentInventoryId == equipmentId)
            .OrderBy(d => d.Status == MaterialDocumentStatus.Current ? 0 : 1)
            .ThenByDescending(d => d.UploadedAt)
            .ToListAsync();

        var userIds = docs.Select(d => d.UploadedByUserId).Distinct().ToList();
        var userMap = await _db.Users
            .Where(u => userIds.Contains(u.Id))
            .ToDictionaryAsync(u => u.Id, u => u.FullName);

        await RecordAccessAsync(0, equipmentId, requestingUserId, EquipmentDocumentAccessAction.View);

        return docs.Select(d => ToDto(d, userMap.GetValueOrDefault(d.UploadedByUserId, "Unknown"))).ToList();
    }

    // ---- Upload ----

    public async Task<EquipmentDocumentDto> UploadAsync(int equipmentId, UploadEquipmentDocumentRequest request, int uploadingUserId)
    {
        var equipment = await _db.EquipmentInventories.FindAsync(equipmentId)
            ?? throw new InvalidOperationException($"Equipment {equipmentId} not found.");

        // Server-side file validation.
        var firstBytes = request.Content.Take(16).ToArray();
        var error = _validator.Validate(request.OriginalFileName, request.DeclaredContentType, request.Content.Length, firstBytes);
        if (error != null)
            throw new InvalidOperationException(error);

        var ext = Path.GetExtension(request.OriginalFileName).ToLowerInvariant();
        var sha256 = Convert.ToHexString(SHA256.HashData(request.Content));

        var document = new EquipmentDocument
        {
            EquipmentInventoryId = equipmentId,
            DocumentType = request.DocumentType,
            OriginalFileName = SanitiseFileName(request.OriginalFileName),
            StorageKey = "pending",
            FileExtension = ext,
            ContentType = NormaliseMime(request.DeclaredContentType),
            FileSizeBytes = request.Content.Length,
            ContentSha256 = sha256,
            UploadedByUserId = uploadingUserId,
            UploadedAt = DateTime.UtcNow,
            Status = MaterialDocumentStatus.Current
        };

        _db.EquipmentDocuments.Add(document);
        await _db.SaveChangesAsync();

        var storageKey = $"equipment-documents/{equipmentId}/{document.Id}{ext}";
        try
        {
            var savedPath = await _storage.SaveAsync(storageKey, request.Content);
            document.StorageKey = savedPath;
            await _db.SaveChangesAsync();
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "File storage failed for EquipmentDocument {Id} (equipment {EquipmentId}). Rolling back DB record.", document.Id, equipmentId);
            _db.EquipmentDocuments.Remove(document);
            try { await _db.SaveChangesAsync(); } catch { /* best-effort */ }
            throw new InvalidOperationException("Document storage failed. The upload was not completed.", ex);
        }

        _logger.LogInformation("EquipmentDocument {Id} uploaded for equipment {EquipmentId} by user {UserId}.", document.Id, equipmentId, uploadingUserId);

        return await LoadDtoAsync(document.Id);
    }

    // ---- Content retrieval ----

    public async Task<(EquipmentDocumentDto Metadata, byte[] Content)> GetContentAsync(int documentId, int equipmentId, int requestingUserId)
    {
        var document = await _db.EquipmentDocuments
            .FirstOrDefaultAsync(d => d.Id == documentId && d.EquipmentInventoryId == equipmentId)
            ?? throw new InvalidOperationException($"Document {documentId} not found for equipment {equipmentId}.");

        byte[] content;
        try
        {
            content = await _storage.ReadAsync(document.StorageKey);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "File read failed for EquipmentDocument {Id} (key: {Key}).", document.Id, document.StorageKey);
            throw new InvalidOperationException("The document file could not be retrieved.");
        }

        // Integrity verification.
        var computedHash = Convert.ToHexString(SHA256.HashData(content));
        if (!string.Equals(computedHash, document.ContentSha256, StringComparison.OrdinalIgnoreCase))
        {
            _logger.LogError(
                "INTEGRITY FAILURE: EquipmentDocument {Id} (equipment {EquipmentId}) stored hash {Stored} does not match computed hash {Computed}.",
                document.Id, document.EquipmentInventoryId, document.ContentSha256, computedHash);
            await RecordAccessAsync(document.Id, equipmentId, requestingUserId, EquipmentDocumentAccessAction.Download);
            throw new InvalidOperationException("Document integrity check failed. The file may have been altered. Please contact your System Administrator.");
        }

        await RecordAccessAsync(document.Id, equipmentId, requestingUserId, EquipmentDocumentAccessAction.Download);

        var userName = await _db.Users
            .Where(u => u.Id == document.UploadedByUserId)
            .Select(u => u.FullName)
            .FirstOrDefaultAsync() ?? "Unknown";

        return (ToDto(document, userName), content);
    }

    // ---- Supersession ----

    public async Task<EquipmentDocumentDto> SupersedeAsync(int documentId, int equipmentId, SupersedeEquipmentDocumentRequest request, int actingUserId)
    {
        if (string.IsNullOrWhiteSpace(request.Reason))
            throw new InvalidOperationException("A supersession reason is required.");

        var old = await _db.EquipmentDocuments
            .FirstOrDefaultAsync(d => d.Id == documentId && d.EquipmentInventoryId == equipmentId)
            ?? throw new InvalidOperationException($"Document {documentId} not found for equipment {equipmentId}.");

        if (old.Status == MaterialDocumentStatus.Voided)
            throw new InvalidOperationException("A voided document cannot be superseded. Upload a new document instead.");

        var firstBytes = request.Content.Take(16).ToArray();
        var error = _validator.Validate(request.OriginalFileName, request.DeclaredContentType, request.Content.Length, firstBytes);
        if (error != null)
            throw new InvalidOperationException(error);

        var ext = Path.GetExtension(request.OriginalFileName).ToLowerInvariant();
        var sha256 = Convert.ToHexString(SHA256.HashData(request.Content));
        var now = DateTime.UtcNow;

        var newDoc = new EquipmentDocument
        {
            EquipmentInventoryId = equipmentId,
            DocumentType = old.DocumentType,
            OriginalFileName = SanitiseFileName(request.OriginalFileName),
            StorageKey = "pending",
            FileExtension = ext,
            ContentType = NormaliseMime(request.DeclaredContentType),
            FileSizeBytes = request.Content.Length,
            ContentSha256 = sha256,
            UploadedByUserId = actingUserId,
            UploadedAt = now,
            Status = MaterialDocumentStatus.Current
        };
        _db.EquipmentDocuments.Add(newDoc);

        old.Status = MaterialDocumentStatus.Superseded;
        old.SupersededAt = now;
        old.SupersededByUserId = actingUserId;
        old.SupersessionReason = request.Reason.Trim();

        await _db.SaveChangesAsync();

        old.SupersededByDocumentId = newDoc.Id;

        var storageKey = $"equipment-documents/{equipmentId}/{newDoc.Id}{ext}";
        try
        {
            var savedPath = await _storage.SaveAsync(storageKey, request.Content);
            newDoc.StorageKey = savedPath;
            await _db.SaveChangesAsync();
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "File storage failed during supersession for EquipmentDocument {OldId} -> {NewId}.", documentId, newDoc.Id);
            old.Status = MaterialDocumentStatus.Current;
            old.SupersededAt = null;
            old.SupersededByUserId = null;
            old.SupersessionReason = null;
            old.SupersededByDocumentId = null;
            _db.EquipmentDocuments.Remove(newDoc);
            try { await _db.SaveChangesAsync(); } catch { /* best-effort */ }
            throw new InvalidOperationException("Replacement file storage failed. The supersession was not completed.", ex);
        }

        _logger.LogInformation("EquipmentDocument {OldId} superseded by {NewId} for equipment {EquipmentId} by user {UserId}.", documentId, newDoc.Id, equipmentId, actingUserId);

        return await LoadDtoAsync(newDoc.Id);
    }

    // ---- Void ----

    public async Task<EquipmentDocumentDto> VoidAsync(int documentId, int equipmentId, VoidEquipmentDocumentRequest request, int actingUserId)
    {
        if (string.IsNullOrWhiteSpace(request.Reason))
            throw new InvalidOperationException("A void reason is required.");

        var document = await _db.EquipmentDocuments
            .FirstOrDefaultAsync(d => d.Id == documentId && d.EquipmentInventoryId == equipmentId)
            ?? throw new InvalidOperationException($"Document {documentId} not found for equipment {equipmentId}.");

        if (document.Status == MaterialDocumentStatus.Voided)
            throw new InvalidOperationException("This document is already voided.");

        document.Status = MaterialDocumentStatus.Voided;
        document.VoidedAt = DateTime.UtcNow;
        document.VoidedByUserId = actingUserId;
        document.VoidReason = request.Reason.Trim();

        await _db.SaveChangesAsync();

        _logger.LogInformation("EquipmentDocument {Id} voided for equipment {EquipmentId} by user {UserId}.", document.Id, equipmentId, actingUserId);

        var userName = await _db.Users
            .Where(u => u.Id == document.UploadedByUserId)
            .Select(u => u.FullName)
            .FirstOrDefaultAsync() ?? "Unknown";

        return ToDto(document, userName);
    }

    // ---- Private helpers ----

    private async Task RecordAccessAsync(int documentId, int equipmentId, int userId, EquipmentDocumentAccessAction action)
    {
        _db.EquipmentDocumentAccessLogs.Add(new EquipmentDocumentAccessLog
        {
            DocumentId = documentId,
            EquipmentInventoryId = equipmentId,
            UserId = userId,
            AccessedAt = DateTime.UtcNow,
            Action = action
        });
        try { await _db.SaveChangesAsync(); } catch (Exception ex)
        {
            _logger.LogWarning(ex, "Failed to record document access log for equipment document {Id}.", documentId);
        }
    }

    private async Task<EquipmentDocumentDto> LoadDtoAsync(int documentId)
    {
        var doc = await _db.EquipmentDocuments
            .FirstOrDefaultAsync(d => d.Id == documentId)
            ?? throw new InvalidOperationException($"Equipment document {documentId} not found.");

        var userName = await _db.Users
            .Where(u => u.Id == doc.UploadedByUserId)
            .Select(u => u.FullName)
            .FirstOrDefaultAsync() ?? "Unknown";

        return ToDto(doc, userName);
    }

    private static EquipmentDocumentDto ToDto(EquipmentDocument d, string? uploadedByName = null) => new(
        d.Id, d.EquipmentInventoryId, d.DocumentType,
        d.OriginalFileName, d.FileExtension, d.ContentType, d.FileSizeBytes,
        d.ContentSha256,
        d.UploadedByUserId, uploadedByName ?? d.UploadedByUser?.FullName ?? "Unknown", d.UploadedAt,
        d.Status,
        d.SupersededByDocumentId, d.SupersededAt, d.SupersededByUserId, d.SupersessionReason,
        d.VoidedAt, d.VoidedByUserId, d.VoidReason);

    private static string SanitiseFileName(string name) =>
        Path.GetFileName(name).Trim();

    private static string NormaliseMime(string mime) =>
        mime.Split(';')[0].Trim().ToLowerInvariant();
}
