using System.Security.Cryptography;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using MicroLIMS.Domain.Entities;
using MicroLIMS.Domain.Enums;
using MicroLIMS.Infrastructure.Storage;
using MicroLIMS.Persistence.DbContext;

namespace MicroLIMS.Application.Services;

public record UploadOosInvestigationDocumentRequest(
    string OriginalFileName,
    string DeclaredContentType,
    byte[] Content);

public record SupersedeOosInvestigationDocumentRequest(
    string OriginalFileName,
    string DeclaredContentType,
    byte[] Content,
    string Reason);

public record VoidOosInvestigationDocumentRequest(string Reason);

public record OosInvestigationDocumentDto(
    int Id,
    string OosGroupCode,
    string OriginalFileName,
    string FileExtension,
    string ContentType,
    long FileSizeBytes,
    string ContentSha256,
    int UploadedByUserId,
    string UploadedByName,
    DateTime UploadedAt,
    MaterialDocumentStatus Status,
    int? SupersededByDocumentId,
    DateTime? SupersededAt,
    int? SupersededByUserId,
    string? SupersessionReason,
    DateTime? VoidedAt,
    int? VoidedByUserId,
    string? VoidReason);

// Service managing the controlled document lifecycle for OOS Lab Investigation Reports.
// Reuses the shared IFileStorageService and MaterialDocumentFileValidator.
//
// Key principles:
// 1. Files are NEVER overwritten on disk.
// 2. Storage keys are generated by the server: oos-investigations/{oosGroupCode}/{documentId}{ext}
// 3. Document integrity is checked via SHA-256 on every content retrieval.
// 4. Supersession atomically marks the previous document Superseded and creates a new Current document.
// 5. Voiding retains the file and metadata for audit but marks the document Voided.
public class OosInvestigationDocumentService
{
    private readonly MicroLimsDbContext _db;
    private readonly IFileStorageService _storage;
    private readonly MaterialDocumentFileValidator _validator;
    private readonly ILogger<OosInvestigationDocumentService> _logger;

    public OosInvestigationDocumentService(
        MicroLimsDbContext db,
        IFileStorageService storage,
        MaterialDocumentFileValidator validator,
        ILogger<OosInvestigationDocumentService> logger)
    {
        _db = db;
        _storage = storage;
        _validator = validator;
        _logger = logger;
    }

    public async Task<List<OosInvestigationDocumentDto>> GetDocumentsAsync(string oosGroupCode)
    {
        var groupExists = await _db.Samples.AnyAsync(s => s.OosGroupCode == oosGroupCode);
        if (!groupExists)
            throw new InvalidOperationException($"OOS group \"{oosGroupCode}\" not found.");

        var docs = await _db.OosInvestigationDocuments
            .Where(d => d.OosGroupCode == oosGroupCode)
            .OrderBy(d => d.Status == MaterialDocumentStatus.Current ? 0 : 1)
            .ThenByDescending(d => d.UploadedAt)
            .ToListAsync();

        var userIds = docs.Select(d => d.UploadedByUserId).Distinct().ToList();
        var userMap = await _db.Users
            .Where(u => userIds.Contains(u.Id))
            .ToDictionaryAsync(u => u.Id, u => u.FullName);

        return docs.Select(d => ToDto(d, userMap.GetValueOrDefault(d.UploadedByUserId, "Unknown"))).ToList();
    }

    public async Task<OosInvestigationDocumentDto> UploadAsync(string oosGroupCode, UploadOosInvestigationDocumentRequest request, int uploadingUserId)
    {
        var groupExists = await _db.Samples.AnyAsync(s => s.OosGroupCode == oosGroupCode);
        if (!groupExists)
            throw new InvalidOperationException($"OOS group \"{oosGroupCode}\" not found.");

        var firstBytes = request.Content.Take(16).ToArray();
        var error = _validator.Validate(request.OriginalFileName, request.DeclaredContentType, request.Content.Length, firstBytes);
        if (error != null)
            throw new InvalidOperationException(error);

        var ext = Path.GetExtension(request.OriginalFileName).ToLowerInvariant();
        var sha256 = Convert.ToHexString(SHA256.HashData(request.Content));

        var document = new OosInvestigationDocument
        {
            OosGroupCode = oosGroupCode,
            OriginalFileName = SanitiseFileName(request.OriginalFileName),
            StorageKey = "pending",
            FileExtension = ext,
            ContentType = NormaliseMime(request.DeclaredContentType),
            FileSizeBytes = request.Content.Length,
            ContentSha256 = sha256,
            UploadedByUserId = uploadingUserId,
            UploadedAt = DateTime.UtcNow,
            Status = MaterialDocumentStatus.Current
        };

        _db.OosInvestigationDocuments.Add(document);
        await _db.SaveChangesAsync();

        var storageKey = $"oos-investigations/{oosGroupCode}/{document.Id}{ext}";
        try
        {
            var savedPath = await _storage.SaveAsync(storageKey, request.Content);
            document.StorageKey = savedPath;
            await _db.SaveChangesAsync();
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "File storage failed for OosInvestigationDocument {Id} (group {GroupCode}). Rolling back DB record.", document.Id, oosGroupCode);
            _db.OosInvestigationDocuments.Remove(document);
            try { await _db.SaveChangesAsync(); } catch { /* best-effort */ }
            throw new InvalidOperationException("Document storage failed. The upload was not completed.", ex);
        }

        _logger.LogInformation("OosInvestigationDocument {Id} uploaded for OOS group {GroupCode} by user {UserId}.", document.Id, oosGroupCode, uploadingUserId);

        return await LoadDtoAsync(document.Id);
    }

    public async Task<(OosInvestigationDocumentDto Metadata, byte[] Content)> GetContentAsync(int documentId, string oosGroupCode, int requestingUserId)
    {
        var document = await _db.OosInvestigationDocuments
            .FirstOrDefaultAsync(d => d.Id == documentId && d.OosGroupCode == oosGroupCode)
            ?? throw new InvalidOperationException($"Document {documentId} not found for OOS group {oosGroupCode}.");

        byte[] content;
        try
        {
            content = await _storage.ReadAsync(document.StorageKey);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "File read failed for OosInvestigationDocument {Id} (key: {Key}).", document.Id, document.StorageKey);
            throw new InvalidOperationException("The document file could not be retrieved.");
        }

        var computedHash = Convert.ToHexString(SHA256.HashData(content));
        if (!string.Equals(computedHash, document.ContentSha256, StringComparison.OrdinalIgnoreCase))
        {
            _logger.LogError(
                "INTEGRITY FAILURE: OosInvestigationDocument {Id} (group {GroupCode}) stored hash {Stored} does not match computed hash {Computed}.",
                document.Id, document.OosGroupCode, document.ContentSha256, computedHash);
            throw new InvalidOperationException("Document integrity check failed. The file may have been altered. Please contact your System Administrator.");
        }

        var userName = await _db.Users
            .Where(u => u.Id == document.UploadedByUserId)
            .Select(u => u.FullName)
            .FirstOrDefaultAsync() ?? "Unknown";

        return (ToDto(document, userName), content);
    }

    public async Task<OosInvestigationDocumentDto> SupersedeAsync(int documentId, string oosGroupCode, SupersedeOosInvestigationDocumentRequest request, int actingUserId)
    {
        if (string.IsNullOrWhiteSpace(request.Reason))
            throw new InvalidOperationException("A supersession reason is required.");

        var old = await _db.OosInvestigationDocuments
            .FirstOrDefaultAsync(d => d.Id == documentId && d.OosGroupCode == oosGroupCode)
            ?? throw new InvalidOperationException($"Document {documentId} not found for OOS group {oosGroupCode}.");

        if (old.Status == MaterialDocumentStatus.Voided)
            throw new InvalidOperationException("A voided document cannot be superseded. Upload a new document instead.");

        var firstBytes = request.Content.Take(16).ToArray();
        var error = _validator.Validate(request.OriginalFileName, request.DeclaredContentType, request.Content.Length, firstBytes);
        if (error != null)
            throw new InvalidOperationException(error);

        var ext = Path.GetExtension(request.OriginalFileName).ToLowerInvariant();
        var sha256 = Convert.ToHexString(SHA256.HashData(request.Content));
        var now = DateTime.UtcNow;

        var newDoc = new OosInvestigationDocument
        {
            OosGroupCode = oosGroupCode,
            OriginalFileName = SanitiseFileName(request.OriginalFileName),
            StorageKey = "pending",
            FileExtension = ext,
            ContentType = NormaliseMime(request.DeclaredContentType),
            FileSizeBytes = request.Content.Length,
            ContentSha256 = sha256,
            UploadedByUserId = actingUserId,
            UploadedAt = now,
            Status = MaterialDocumentStatus.Current
        };
        _db.OosInvestigationDocuments.Add(newDoc);

        old.Status = MaterialDocumentStatus.Superseded;
        old.SupersededAt = now;
        old.SupersededByUserId = actingUserId;
        old.SupersessionReason = request.Reason.Trim();

        await _db.SaveChangesAsync();

        old.SupersededByDocumentId = newDoc.Id;

        var storageKey = $"oos-investigations/{oosGroupCode}/{newDoc.Id}{ext}";
        try
        {
            var savedPath = await _storage.SaveAsync(storageKey, request.Content);
            newDoc.StorageKey = savedPath;
            await _db.SaveChangesAsync();
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "File storage failed during supersession for OosInvestigationDocument {OldId} -> {NewId}.", documentId, newDoc.Id);
            old.Status = MaterialDocumentStatus.Current;
            old.SupersededAt = null;
            old.SupersededByUserId = null;
            old.SupersessionReason = null;
            old.SupersededByDocumentId = null;
            _db.OosInvestigationDocuments.Remove(newDoc);
            try { await _db.SaveChangesAsync(); } catch { /* best-effort */ }
            throw new InvalidOperationException("Replacement file storage failed. The supersession was not completed.", ex);
        }

        _logger.LogInformation("OosInvestigationDocument {OldId} superseded by {NewId} for group {GroupCode} by user {UserId}.", documentId, newDoc.Id, oosGroupCode, actingUserId);

        return await LoadDtoAsync(newDoc.Id);
    }

    public async Task<OosInvestigationDocumentDto> VoidAsync(int documentId, string oosGroupCode, VoidOosInvestigationDocumentRequest request, int actingUserId)
    {
        if (string.IsNullOrWhiteSpace(request?.Reason))
            throw new InvalidOperationException("A void reason is required.");

        var document = await _db.OosInvestigationDocuments
            .FirstOrDefaultAsync(d => d.Id == documentId && d.OosGroupCode == oosGroupCode)
            ?? throw new InvalidOperationException($"Document {documentId} not found for OOS group {oosGroupCode}.");

        if (document.Status == MaterialDocumentStatus.Voided)
            throw new InvalidOperationException("This document is already voided.");

        document.Status = MaterialDocumentStatus.Voided;
        document.VoidedAt = DateTime.UtcNow;
        document.VoidedByUserId = actingUserId;
        document.VoidReason = request.Reason.Trim();

        await _db.SaveChangesAsync();

        _logger.LogInformation("OosInvestigationDocument {Id} voided for group {GroupCode} by user {UserId}.", document.Id, oosGroupCode, actingUserId);

        var userName = await _db.Users
            .Where(u => u.Id == document.UploadedByUserId)
            .Select(u => u.FullName)
            .FirstOrDefaultAsync() ?? "Unknown";

        return ToDto(document, userName);
    }

    private async Task<OosInvestigationDocumentDto> LoadDtoAsync(int documentId)
    {
        var doc = await _db.OosInvestigationDocuments
            .FirstOrDefaultAsync(d => d.Id == documentId)
            ?? throw new InvalidOperationException($"OOS investigation document {documentId} not found.");

        var userName = await _db.Users
            .Where(u => u.Id == doc.UploadedByUserId)
            .Select(u => u.FullName)
            .FirstOrDefaultAsync() ?? "Unknown";

        return ToDto(doc, userName);
    }

    private static OosInvestigationDocumentDto ToDto(OosInvestigationDocument d, string? uploadedByName = null) => new(
        d.Id, d.OosGroupCode,
        d.OriginalFileName, d.FileExtension, d.ContentType, d.FileSizeBytes,
        d.ContentSha256,
        d.UploadedByUserId, uploadedByName ?? d.UploadedByUser?.FullName ?? "Unknown", d.UploadedAt,
        d.Status,
        d.SupersededByDocumentId, d.SupersededAt, d.SupersededByUserId, d.SupersessionReason,
        d.VoidedAt, d.VoidedByUserId, d.VoidReason);

    private static string SanitiseFileName(string name) =>
        Path.GetFileName(name).Trim();

    private static string NormaliseMime(string mime) =>
        mime.Split(';')[0].Trim().ToLowerInvariant();
}
