using System.Text.RegularExpressions;
using Npgsql;

namespace MicroLIMS.Tests.Fixtures;

// Decides whether PostgreSQL-backed tests can run, and - critically -
// owns the name of the database they are allowed to touch.
//
// The safety property this type exists to guarantee:
//
//   The caller supplies a SERVER to connect to. It never supplies a
//   database name. The name is generated here, per run, and every
//   destructive statement is validated against the generated pattern
//   first.
//
// That is why a misconfigured environment cannot drop the application
// database: there is no configuration value that names the target. The
// old fixture hard-coded both a privileged credential and a fixed
// database name, and dropped that name unconditionally.
public static class PostgresTestConfiguration
{
    // A full Npgsql connection string pointing at a MAINTENANCE database
    // (normally "postgres") on a server that exists only for testing.
    // Never committed - see the test README section in the final report.
    public const string ConnectionStringVariable = "MICROLIMS_TEST_POSTGRES";

    // Every test database this fixture creates carries this prefix and a
    // per-run suffix. Nothing outside this shape may ever be dropped.
    private const string TestDatabasePrefix = "microlims_test_";

    private static readonly Regex GeneratedNamePattern =
        new($"^{TestDatabasePrefix}[0-9a-f]{{32}}$", RegexOptions.Compiled);

    // Names that must never be dropped even if some future change managed
    // to produce one. Belt and braces on top of the pattern check: the
    // pattern alone already excludes all of these.
    private static readonly string[] ReservedNames =
    {
        "postgres", "template0", "template1", "defaultdb", "limsv2"
    };

    public static string? AdminConnectionString =>
        Environment.GetEnvironmentVariable(ConnectionStringVariable) is { Length: > 0 } value
            ? value
            : null;

    public static bool IsConfigured => AdminConnectionString is not null;

    public static string SkipReason =>
        $"PostgreSQL integration tests need a disposable test server. Set {ConnectionStringVariable} " +
        "to a connection string for its maintenance database (for example " +
        "\"Host=localhost;Port=5432;Database=postgres;Username=postgres;Password=<secret>\"). " +
        "The test database itself is created and dropped per run and is never named by configuration.";

    // A fresh, collision-proof name for each run. Two developers, two CI
    // jobs and two processes on one machine cannot collide.
    public static string NewTestDatabaseName() =>
        TestDatabasePrefix + Guid.NewGuid().ToString("n");

    // The single gate every destructive statement passes through.
    // Throws rather than returning false: a caller that gets this wrong
    // must stop, not continue with an unvalidated name.
    public static void EnsureSafeToDrop(string databaseName, string adminConnectionString)
    {
        if (string.IsNullOrWhiteSpace(databaseName))
            throw new InvalidOperationException("Refusing to drop a database with no name.");

        if (!GeneratedNamePattern.IsMatch(databaseName))
            throw new InvalidOperationException(
                $"Refusing to drop '{databaseName}': it was not generated by " +
                $"{nameof(PostgresTestConfiguration)}.{nameof(NewTestDatabaseName)}. Only databases " +
                $"matching {TestDatabasePrefix}<32 hex chars> may be dropped by the test fixture.");

        if (ReservedNames.Contains(databaseName, StringComparer.OrdinalIgnoreCase))
            throw new InvalidOperationException($"Refusing to drop reserved database '{databaseName}'.");

        // The maintenance database we are connected through is by
        // definition not disposable - and PostgreSQL would refuse anyway.
        var adminDatabase = TryReadDatabase(adminConnectionString);
        if (adminDatabase is not null && string.Equals(adminDatabase, databaseName, StringComparison.OrdinalIgnoreCase))
            throw new InvalidOperationException(
                $"Refusing to drop '{databaseName}': it is the maintenance database the fixture connects through.");
    }

    // Builds the connection string for the isolated test database from the
    // supplied server connection, so credentials live in exactly one place.
    public static string BuildTestConnectionString(string adminConnectionString, string testDatabaseName)
    {
        EnsureSafeToDrop(testDatabaseName, adminConnectionString);

        return new NpgsqlConnectionStringBuilder(adminConnectionString)
        {
            Database = testDatabaseName,
            IncludeErrorDetail = true
        }.ConnectionString;
    }

    private static string? TryReadDatabase(string connectionString)
    {
        try
        {
            return new NpgsqlConnectionStringBuilder(connectionString).Database;
        }
        catch (ArgumentException)
        {
            // A malformed connection string is the caller's problem, and
            // the pattern check above has already done the real work.
            return null;
        }
    }
}
