using MicroLIMS.Domain.Enums;

namespace MicroLIMS.Domain.Entities;

// One correlated "thing that went wrong" - the unit the admin actually
// looks at on the error monitoring page. Every ErrorLog row sharing a
// CorrelationId attaches here instead of showing as a disconnected row.
//
// Operational/technical data only - NOT a GxP record. Deliberately
// excluded from CaptureAuditEntries (see MicroLimsDbContext) so technical
// noise never reaches the audit trail, where the immutability triggers
// would also make it unprunable. This table may be pruned per policy.
public class Incident
{
    public Guid Id { get; set; } = Guid.NewGuid();

    // Per-request identifier generated by the correlation middleware.
    // Unrelated to AuditLog.CorrelationId, which is a Guid used to group
    // GxP document-control audit events - the two must never be mixed.
    public string CorrelationId { get; set; } = string.Empty;

    public DateTime FirstSeenUtc { get; set; } = DateTime.UtcNow;
    public DateTime LastSeenUtc { get; set; } = DateTime.UtcNow;

    public IncidentStatus Status { get; set; } = IncidentStatus.Open;

    // Rolled up as the max of the child ErrorLog rows (honouring their
    // SeverityOverride), recomputed each time a row attaches.
    public ErrorSeverity Severity { get; set; } = ErrorSeverity.Info;

    // Short auto-generated description, e.g. "NullReferenceException -
    // POST /api/results". Built from the first attached ErrorLog.
    public string Summary { get; set; } = string.Empty;

    // Set once, when a Critical alert has actually been sent for this
    // incident. Persisted rather than held in memory so a restart cannot
    // resend an alert that already went out, and so one outage producing
    // dozens of ErrorLog rows still produces exactly one email.
    public DateTime? AlertedAtUtc { get; set; }

    public int? ResolvedByUserId { get; set; }
    public User? ResolvedByUser { get; set; }
    public DateTime? ResolvedAtUtc { get; set; }
    public string? ResolutionNotes { get; set; }

    public ICollection<ErrorLog> ErrorLogs { get; set; } = new List<ErrorLog>();
}
