using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging.Abstractions;
using MicroLIMS.Application.Interfaces;
using MicroLIMS.Application.Services;
using MicroLIMS.Domain.Entities;
using MicroLIMS.Domain.Enums;
using MicroLIMS.Infrastructure.Email;
using MicroLIMS.Persistence.DbContext;
using MicroLIMS.Shared.Constants;
using Xunit;

namespace MicroLIMS.Tests.UnitTests;

// The architectural invariant: two separate audit domains.
//
//   Laboratory / GxP activity  -> AuditLog            (regulated evidence)
//   Security / identity events -> SecurityAuditEvent  (security evidence)
//
// RefreshToken CRUD must reach neither - it is a database implementation
// detail, not an event. Meaningful authentication events reach the second
// trail only.
//
// In-memory persistence throughout - nothing destructive.
public class SecurityAuditTrailTests
{
    private const string CurrentPassword = "CurrentPass1!";
    private const string ReplacementPassword = "Replacement2@";
    private const string TestCorrelationId = "corr-0123456789abcdef";

    // Stands in for the HTTP-backed context so correlation, IP and user
    // agent can be asserted without an ASP.NET request.
    private sealed class StubRequestContext : ISecurityRequestContext
    {
        public string? CorrelationId => TestCorrelationId;
        public string? IpAddress => "203.0.113.7";
        public string? UserAgent => "MicroLIMS-Test/1.0";
        public string? RequestPath => "/api/auth/login";
        public string Source => "Api";
    }

    private static MicroLimsDbContext CreateDbContext()
    {
        var options = new DbContextOptionsBuilder<MicroLimsDbContext>()
            .UseInMemoryDatabase(databaseName: Guid.NewGuid().ToString())
            .Options;
        var db = new MicroLimsDbContext(options);

        db.Roles.AddRange(
            new Role { Id = 1, Type = RoleType.SystemAdministrator, Name = "System Administrator" },
            new Role { Id = 2, Type = RoleType.SectionHead, Name = "Section Head" },
            new Role { Id = 4, Type = RoleType.Analyst, Name = "Analyst" }
        );
        db.SaveChanges();
        return db;
    }

    private static (UserService UserService, AuthenticationService AuthService) CreateServices(MicroLimsDbContext db)
    {
        var emailSender = new EmailSender("", 587, "", "", "no-reply@microlims.local", false);
        Func<string, string, IEnumerable<string>, string> tokenIssuer = (id, role, codes) => $"jwt-for-{id}";
        var securityAudit = new SecurityAuditService(db, new StubRequestContext());
        var authService = new AuthenticationService(
            db, tokenIssuer, new PermissionService(db), emailSender,
            NullLogger<AuthenticationService>.Instance, securityAudit);
        return (new UserService(db, authService, securityAudit), authService);
    }

    private static User SeedUser(MicroLimsDbContext db, int id = 10, string username = "analyst1", int roleId = 4)
    {
        var user = new User
        {
            Id = id,
            FullName = "Test Analyst",
            Username = username,
            PasswordHash = BCrypt.Net.BCrypt.HashPassword(CurrentPassword),
            RoleId = roleId,
            IsActive = true
        };
        db.Users.Add(user);
        db.SaveChanges();
        return user;
    }

    private static Task<List<SecurityAuditEvent>> EventsAsync(MicroLimsDbContext db, string eventCode) =>
        db.SecurityAuditEvents.Where(e => e.EventCode == eventCode).ToListAsync();

    // Every GxP row generated by RefreshToken persistence, which must now
    // be none.
    private static Task<List<AuditLog>> RefreshTokenGxpRowsAsync(MicroLimsDbContext db) =>
        db.AuditLogs.Where(a => a.EntityName == nameof(RefreshToken)).ToListAsync();

    // ---------- 1 & 2. RefreshToken no longer contaminates the GxP trail ----------

    [Fact]
    public async Task RefreshTokenPersistence_CreatesNoGxpAuditLog()
    {
        using var db = CreateDbContext();
        SeedUser(db);
        var (_, auth) = CreateServices(db);

        var outcome = await auth.LoginAsync("analyst1", CurrentPassword);
        Assert.True(outcome.Success);

        Assert.Empty(await RefreshTokenGxpRowsAsync(db));
    }

    [Fact]
    public async Task RefreshTokenRotation_CreatesNoGxpAuditLog()
    {
        using var db = CreateDbContext();
        SeedUser(db);
        var (_, auth) = CreateServices(db);
        var login = await auth.LoginAsync("analyst1", CurrentPassword);

        Assert.True((await auth.RefreshAsync(login.RefreshToken!)).Success);

        Assert.Empty(await RefreshTokenGxpRowsAsync(db));
    }

    [Fact]
    public async Task RefreshTokenRevocation_CreatesNoGxpAuditLog()
    {
        using var db = CreateDbContext();
        var user = SeedUser(db);
        var (users, auth) = CreateServices(db);
        await auth.LoginAsync("analyst1", CurrentPassword);

        await users.SetStatusAsync(user.Id, isActive: false, reason: "Suspended", actingUserId: 1);

        Assert.Empty(await RefreshTokenGxpRowsAsync(db));
    }

    // The security trail must not audit itself either, or every event
    // would generate a GxP row about the event.
    [Fact]
    public async Task SecurityAuditEvents_AreNotThemselvesGxpAudited()
    {
        using var db = CreateDbContext();
        SeedUser(db);
        var (_, auth) = CreateServices(db);

        await auth.LoginAsync("analyst1", CurrentPassword);

        Assert.Empty(await db.AuditLogs.Where(a => a.EntityName == nameof(SecurityAuditEvent)).ToListAsync());
    }

    // ---------- 3 & 4. Login events ----------

    [Fact]
    public async Task SuccessfulLogin_RecordsLoginSuccessAndTokenIssued()
    {
        using var db = CreateDbContext();
        var user = SeedUser(db);
        var (_, auth) = CreateServices(db);

        await auth.LoginAsync("analyst1", CurrentPassword);

        var login = Assert.Single(await EventsAsync(db, SecurityEventCodes.LoginSuccess));
        Assert.Equal(SecurityEventOutcome.Success, login.Outcome);
        Assert.Equal(user.Id, login.ActorUserId);
        Assert.Equal(user.Id, login.TargetUserId);
        Assert.Equal("analyst1", login.TargetUsername);

        Assert.Single(await EventsAsync(db, SecurityEventCodes.RefreshTokenIssued));
    }

    [Fact]
    public async Task FailedLogin_WrongPassword_RecordsBadCredentials()
    {
        using var db = CreateDbContext();
        var user = SeedUser(db);
        var (_, auth) = CreateServices(db);

        await auth.LoginAsync("analyst1", "TotallyWrong9!");

        var failure = Assert.Single(await EventsAsync(db, SecurityEventCodes.LoginFailedBadCredentials));
        Assert.Equal(SecurityEventOutcome.Failure, failure.Outcome);
        Assert.Equal(user.Id, failure.TargetUserId);
        Assert.Null(failure.ActorUserId); // nobody is authenticated yet
    }

    [Fact]
    public async Task FailedLogin_UnknownUser_RecordsUnknownUser_WithNoUserId()
    {
        using var db = CreateDbContext();
        SeedUser(db);
        var (_, auth) = CreateServices(db);

        await auth.LoginAsync("nobody-here", CurrentPassword);

        var failure = Assert.Single(await EventsAsync(db, SecurityEventCodes.LoginFailedUnknownUser));
        Assert.Null(failure.TargetUserId);
        Assert.Equal("nobody-here", failure.TargetUsername);
    }

    [Fact]
    public async Task FailedLogin_DisabledAccount_RecordsAccountDisabledCode()
    {
        using var db = CreateDbContext();
        var user = SeedUser(db);
        var (users, _) = CreateServices(db);
        await users.SetStatusAsync(user.Id, isActive: false, reason: "Suspended", actingUserId: 1);

        var (_, auth) = CreateServices(db);
        await auth.LoginAsync("analyst1", CurrentPassword);

        Assert.Single(await EventsAsync(db, SecurityEventCodes.LoginFailedAccountDisabled));
    }

    // ---------- 5. Logout ----------

    [Fact]
    public async Task Logout_RecordsLogoutEvent()
    {
        using var db = CreateDbContext();
        var user = SeedUser(db);
        var (_, auth) = CreateServices(db);
        var login = await auth.LoginAsync("analyst1", CurrentPassword);

        await auth.LogoutAsync(user.Id, login.RefreshToken);

        var logout = Assert.Single(await EventsAsync(db, SecurityEventCodes.Logout));
        Assert.Equal(user.Id, logout.ActorUserId);
        Assert.Equal(user.Id, logout.TargetUserId);
    }

    // ---------- 6 & 7. Password events ----------

    [Fact]
    public async Task PasswordChange_RecordsPasswordChangedAndSessionRevoked()
    {
        using var db = CreateDbContext();
        var user = SeedUser(db);
        var (_, auth) = CreateServices(db);
        await auth.LoginAsync("analyst1", CurrentPassword);

        Assert.True(await auth.ChangePasswordAsync(user.Id, CurrentPassword, ReplacementPassword));

        var changed = Assert.Single(await EventsAsync(db, SecurityEventCodes.PasswordChanged));
        Assert.Equal(user.Id, changed.ActorUserId);
        Assert.Equal(user.Id, changed.TargetUserId);

        // The revocation the password change caused is its own event.
        Assert.Single(await EventsAsync(db, SecurityEventCodes.SessionRevoked));
    }

    [Fact]
    public async Task FailedPasswordChange_RecordsFailureEvent()
    {
        using var db = CreateDbContext();
        var user = SeedUser(db);
        var (_, auth) = CreateServices(db);

        Assert.False(await auth.ChangePasswordAsync(user.Id, "NotMyPassword1!", ReplacementPassword));

        var failure = Assert.Single(await EventsAsync(db, SecurityEventCodes.PasswordChangeFailed));
        Assert.Equal(SecurityEventOutcome.Failure, failure.Outcome);
    }

    [Fact]
    public async Task PasswordReset_RecordsPasswordResetEvent()
    {
        using var db = CreateDbContext();
        var user = SeedUser(db);
        var (_, auth) = CreateServices(db);

        var rawResetToken = Guid.NewGuid().ToString("N");
        db.PasswordResetTokens.Add(new PasswordResetToken
        {
            UserId = user.Id,
            TokenHash = Convert.ToHexString(
                System.Security.Cryptography.SHA256.HashData(System.Text.Encoding.UTF8.GetBytes(rawResetToken))),
            ExpiresAt = DateTime.UtcNow.AddHours(1)
        });
        await db.SaveChangesAsync();

        Assert.True(await auth.ConfirmPasswordResetAsync(rawResetToken, ReplacementPassword));

        var reset = Assert.Single(await EventsAsync(db, SecurityEventCodes.PasswordReset));
        Assert.Equal(user.Id, reset.TargetUserId);
        // Redeeming a reset token is not an authenticated action.
        Assert.Null(reset.ActorUserId);
    }

    // ---------- 8 & 12. Account disable, with actor/target distinction ----------

    [Fact]
    public async Task Disable_RecordsAccountDisabled_WithDistinctActorAndTarget()
    {
        using var db = CreateDbContext();
        var admin = SeedUser(db, id: 1, username: "admin", roleId: 1);
        var target = SeedUser(db, id: 10, username: "analyst1");
        var (users, _) = CreateServices(db);

        await users.SetStatusAsync(target.Id, isActive: false, reason: "Left the laboratory", actingUserId: admin.Id);

        var disabled = Assert.Single(await EventsAsync(db, SecurityEventCodes.AccountDisabled));
        Assert.Equal(admin.Id, disabled.ActorUserId);
        Assert.Equal(target.Id, disabled.TargetUserId);
        Assert.NotEqual(disabled.ActorUserId, disabled.TargetUserId);
        Assert.Equal("analyst1", disabled.TargetUsername);
        Assert.Equal("Left the laboratory", disabled.Reason);
        Assert.False(disabled.ActorIsSystem);
    }

    // The GxP record of the same administrative action must survive - a
    // security event is recorded alongside it, never instead of it.
    [Fact]
    public async Task Disable_StillWritesTheGxpUserDisabledAuditEntry()
    {
        using var db = CreateDbContext();
        var target = SeedUser(db, id: 10, username: "analyst1");
        var (users, _) = CreateServices(db);

        await users.SetStatusAsync(target.Id, isActive: false, reason: "Suspended", actingUserId: 1);

        Assert.Single(await db.AuditLogs
            .Where(a => a.EntityName == nameof(User) && a.Action == "USER_DISABLED")
            .ToListAsync());
    }

    [Fact]
    public async Task Enable_RecordsAccountEnabled()
    {
        using var db = CreateDbContext();
        var target = SeedUser(db, id: 10, username: "analyst1");
        var (users, _) = CreateServices(db);
        await users.SetStatusAsync(target.Id, isActive: false, reason: "Suspended", actingUserId: 1);

        await users.SetStatusAsync(target.Id, isActive: true, reason: "Returned", actingUserId: 1);

        Assert.Single(await EventsAsync(db, SecurityEventCodes.AccountEnabled));
    }

    // ---------- 9. Automatic lockout, actor = system ----------

    [Fact]
    public async Task AutomaticLockout_RecordsAccountLocked_WithSystemActor()
    {
        using var db = CreateDbContext();
        var user = SeedUser(db);
        var (_, auth) = CreateServices(db);

        for (var attempt = 0; attempt < 5; attempt++)
            await auth.LoginAsync("analyst1", "TotallyWrong9!");

        var locked = Assert.Single(await EventsAsync(db, SecurityEventCodes.AccountLocked));
        Assert.True(locked.ActorIsSystem);
        Assert.Null(locked.ActorUserId); // no person locked this account
        Assert.Equal(user.Id, locked.TargetUserId);
        Assert.Contains("Automatic lockout", locked.Reason);
    }

    [Fact]
    public async Task AdministrativeUnlock_RecordsAccountUnlocked()
    {
        using var db = CreateDbContext();
        var target = SeedUser(db, id: 10, username: "analyst1");
        var (users, _) = CreateServices(db);

        await users.UnlockUserAsync(target.Id, "Verified identity by phone", actingUserId: 1);

        var unlocked = Assert.Single(await EventsAsync(db, SecurityEventCodes.AccountUnlocked));
        Assert.Equal(1, unlocked.ActorUserId);
        Assert.Equal(target.Id, unlocked.TargetUserId);
    }

    // ---------- 10. Role change ----------

    [Fact]
    public async Task RoleChange_RecordsRoleChanged_WithBothRolesInMetadata()
    {
        using var db = CreateDbContext();
        var target = SeedUser(db, id: 10, username: "analyst1", roleId: 4);
        var (users, _) = CreateServices(db);

        await users.ChangeRoleAsync(target.Id, newRoleId: 2, reason: "Promoted", actingUserId: 1);

        var changed = Assert.Single(await EventsAsync(db, SecurityEventCodes.RoleChanged));
        Assert.Equal(1, changed.ActorUserId);
        Assert.Equal(target.Id, changed.TargetUserId);
        Assert.Equal("Promoted", changed.Reason);
        Assert.Contains("Analyst", changed.Metadata);
        Assert.Contains("Section Head", changed.Metadata);
    }

    // ---------- 11. No credentials ever reach the trail ----------

    [Fact]
    public async Task SecurityEvents_NeverContainRawTokensOrPasswords()
    {
        using var db = CreateDbContext();
        var user = SeedUser(db);
        var (users, auth) = CreateServices(db);

        // Exercise every flow that handles a credential or a token.
        var login = await auth.LoginAsync("analyst1", CurrentPassword);
        var rotated = await auth.RefreshAsync(login.RefreshToken!);
        await auth.LogoutAsync(user.Id, rotated.RefreshToken);
        await auth.LoginAsync("analyst1", "TotallyWrong9!");
        await auth.ChangePasswordAsync(user.Id, CurrentPassword, ReplacementPassword);
        await users.SetStatusAsync(user.Id, isActive: false, reason: "Done", actingUserId: 1);

        var secrets = new[]
        {
            CurrentPassword, ReplacementPassword, "TotallyWrong9!",
            login.RefreshToken!, rotated.RefreshToken!, login.Token!,
            (await db.Users.FirstAsync(u => u.Id == user.Id)).PasswordHash
        };

        var events = await db.SecurityAuditEvents.ToListAsync();
        Assert.NotEmpty(events);

        foreach (var e in events)
        {
            var serialised = string.Join("|", e.EventCode, e.TargetUsername, e.CorrelationId,
                e.IpAddress, e.UserAgent, e.RequestPath, e.Source, e.Reason, e.Metadata);

            foreach (var secret in secrets)
                Assert.DoesNotContain(secret, serialised);
        }
    }

    // ---------- 13. Correlation and request context ----------

    [Fact]
    public async Task SecurityEvents_CarryTheTechnicalCorrelationIdAndRequestContext()
    {
        using var db = CreateDbContext();
        SeedUser(db);
        var (_, auth) = CreateServices(db);

        await auth.LoginAsync("analyst1", CurrentPassword);

        var login = Assert.Single(await EventsAsync(db, SecurityEventCodes.LoginSuccess));
        Assert.Equal(TestCorrelationId, login.CorrelationId);
        Assert.Equal("203.0.113.7", login.IpAddress);
        Assert.Equal("MicroLIMS-Test/1.0", login.UserAgent);
        Assert.Equal("/api/auth/login", login.RequestPath);
        Assert.Equal("Api", login.Source);
    }

    // With no request in flight the trail still records the event, just
    // without HTTP context - background work must not be dropped.
    [Fact]
    public async Task SecurityEvents_OutsideARequest_AreStillRecordedAsSystemSource()
    {
        using var db = CreateDbContext();
        SeedUser(db);
        var emailSender = new EmailSender("", 587, "", "", "no-reply@microlims.local", false);
        Func<string, string, IEnumerable<string>, string> tokenIssuer = (id, role, codes) => "jwt";
        var auth = new AuthenticationService(
            db, tokenIssuer, new PermissionService(db), emailSender,
            NullLogger<AuthenticationService>.Instance,
            new SecurityAuditService(db, new SystemSecurityRequestContext()));

        await auth.LoginAsync("analyst1", CurrentPassword);

        var login = Assert.Single(await EventsAsync(db, SecurityEventCodes.LoginSuccess));
        Assert.Equal("System", login.Source);
        Assert.Null(login.CorrelationId);
    }

    // ---------- Refresh rejections are security events too ----------

    // A locked account whose token was never revoked is the case that
    // reaches the account-state check: the token row is still active, so
    // only the re-read of the user stops the refresh.
    [Fact]
    public async Task RefreshRejectedForLockedAccount_RecordsAccountBlocked()
    {
        using var db = CreateDbContext();
        var user = SeedUser(db);
        var (_, auth) = CreateServices(db);
        var login = await auth.LoginAsync("analyst1", CurrentPassword);

        var stored = await db.Users.FirstAsync(u => u.Id == user.Id);
        stored.LockedUntil = DateTime.UtcNow.AddMinutes(15);
        await db.SaveChangesAsync();

        await auth.RefreshAsync(login.RefreshToken!);

        var rejected = Assert.Single(await EventsAsync(db, SecurityEventCodes.RefreshRejectedAccountBlocked));
        Assert.Equal(SecurityEventOutcome.Failure, rejected.Outcome);
        Assert.Equal(user.Id, rejected.TargetUserId);
        Assert.Equal("Account is locked.", rejected.Reason);
    }

    // Disabling revokes the token first, so a later refresh is rejected as
    // an invalid token rather than a blocked account - the earlier and
    // more precise reason. Either way the rejection is recorded.
    [Fact]
    public async Task RefreshAfterDisable_RecordsInvalidTokenRejection()
    {
        using var db = CreateDbContext();
        var user = SeedUser(db);
        var (users, auth) = CreateServices(db);
        var login = await auth.LoginAsync("analyst1", CurrentPassword);

        await users.SetStatusAsync(user.Id, isActive: false, reason: "Suspended", actingUserId: 1);
        await auth.RefreshAsync(login.RefreshToken!);

        var rejected = Assert.Single(await EventsAsync(db, SecurityEventCodes.RefreshRejectedInvalidToken));
        Assert.Equal(SecurityEventOutcome.Failure, rejected.Outcome);
        Assert.Equal(user.Id, rejected.TargetUserId);
    }

    [Fact]
    public async Task RefreshWithUnrecognisedToken_RecordsTheRejection_WithoutTheTokenValue()
    {
        using var db = CreateDbContext();
        SeedUser(db);
        var (_, auth) = CreateServices(db);

        await auth.RefreshAsync("some-token-that-was-never-issued");

        var rejected = Assert.Single(await EventsAsync(db, SecurityEventCodes.RefreshRejectedInvalidToken));
        Assert.Null(rejected.TargetUserId);
        Assert.DoesNotContain("some-token-that-was-never-issued", rejected.Reason ?? string.Empty);
    }

    [Fact]
    public async Task SuccessfulRefresh_RecordsRotation()
    {
        using var db = CreateDbContext();
        SeedUser(db);
        var (_, auth) = CreateServices(db);
        var login = await auth.LoginAsync("analyst1", CurrentPassword);

        Assert.True((await auth.RefreshAsync(login.RefreshToken!)).Success);

        Assert.Single(await EventsAsync(db, SecurityEventCodes.RefreshTokenRotated));
    }
}
